# dhcpcd configuration for Android Wi-Fi interface
# See dhcpcd.conf(5) for details.
duid
# Disable solicitation of IPv6 Router Advertisements
#noipv6rs
dhcp6
ipv6only
ipv6ra_accept_nopublic
#ipv6rs
#ipv6ra_own
env wpa_supplicant_conf=/system/etc/wifi/
interface wlan0
ipv6ra_accept_nopublic
# dhcpcd-run-hooks uses these options.
#option subnet_mask, routers, domain_name_servers, interface_mtu
#option domain_name_servers, monotime
#nooption vendclass, vendorclassid, vendopt, vendor
fqdn
#hostname