
#
/system/framework/framework.jar
#
/system/framework/framework.jar
0
(/system/framework/framework-graphics.jar34
0
(/system/framework/framework-graphics.jar34

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
"
/system/framework/tcmiface.jar
"
/system/framework/tcmiface.jar
'
#/system/framework/telephony-ext.jar
'
#/system/framework/telephony-ext.jar
#
/system/framework/WfdCommon.jar
#
/system/framework/WfdCommon.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/QPerformance.jar
&
"/system/framework/QPerformance.jar
'
#/system/framework/UxPerformance.jar
'
#/system/framework/UxPerformance.jar
1
-/system/framework/com.symbol.ramexpansion.jar
1
-/system/framework/com.symbol.ramexpansion.jar
2
./system/framework/com.symbol.fusionmanager.jar
2
./system/framework/com.symbol.fusionmanager.jar
1
-/system/framework/com.symbol.fusionnative.jar
1
-/system/framework/com.symbol.fusionnative.jar
7
3/system/framework/com.zebra.fusionsystemwrapper.jar
7
3/system/framework/com.zebra.fusionsystemwrapper.jar
.
*/system/framework/ztelephony_framework.jar
.
*/system/framework/ztelephony_framework.jar
-
)/system/framework/zebra_radio_wrapper.jar
-
)/system/framework/zebra_radio_wrapper.jar
2
./system/framework/zebra_radio_wrapper_impl.jar
2
./system/framework/zebra_radio_wrapper_impl.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar